### PR TITLE
ViT pytorch speedster notebook added

### PR DESCRIPTION
**Pull request by VinishUchiha**
I added a new notebook demonstrating how to optimize PyTorch VisionTransformer using Speedster.

### CODE REVIEW

**Comment by nebuly-ai** [comment]
Thank you @VinishUchiha for creating the notebook! It is much appreciated.

**Comment by mfumanelli** [comment]
Hi @VinishUchiha! Thanks a lot for this notebook ❤️ you did an amazing job! I ask if you can just make a couple of changes.

This sentence: 

> Let first test the optimization without accuracy loss (metric_drop_ths=0, default value), and then apply further accelerate it under the constrained of losing up to 2% of accuracy (metric = "accuracy", metric_drop_ths = 0.02).

Change it to something like:

> Let's first test the optimization without any loss in accuracy (metric_drop_ths=0, which is the default value), and then attempt to further accelerate it while constraining the loss of accuracy to a maximum of 2% (metric = 'accuracy', metric_drop_ths = 0.02).

And here move the model to the device:

```
# Try the optimized model
x = torch.randn(1, 3, 256, 256).to(device)
model.to(device).eval()
res_optimized = optimized_model(x)
res_original = model(x)
```
Thank you very much! 🦄 🌈

**Comment by VinishUchiha** [comment]
Sure @mfumanelli

**Comment by VinishUchiha** [comment]
@mfumanelli I modified the text as you suggested. but the second change, the model is already moved to the device.
```
# Load a ViT model
model = ViT(
    image_size = 256,
    patch_size = 32,
    num_classes = 1000,
    dim = 1024,
    depth = 6,
    heads = 16,
    mlp_dim = 2048,
    dropout = 0.1,
    emb_dropout = 0.1
).to(device)
```
Could you please check that?

**Comment by VinishUchiha** [comment]
Understood @mfumanelli. I will do the change that you before mentioned.

**Comment by mfumanelli** [comment]
Perfect! LGTM, thank you @VinishUchiha, great work! ❤️

**Pull request merged**
